#! /bin/sh

IPTABLES=/sbin/iptables
WWW_SERVER_HOST=172.16.17.200
WWW_SERVER_PORT=80
TUN_INTERFACE=of0

$IPTABLES -t nat -A PREROUTING -i $TUN_INTERFACE -p tcp --dport 80 -j DNAT --to $WWW_SERVER_HOST:$WWW_SERVER_PORT
#$IPTABLES -A FORWARD -i $TUN_INTERFACE -p tcp --dport 80 -j ACCEPT
#$IPTABLES -A FORWARD -i $TUN_INTERFACE -j DROP
