#! /usr/bin/env ruby
#
# dump forwarding database
#


require 'rubygems'
require 'memcache'


class DumpFdb < MemCache
  def slabs server
    stats = {}
    with_socket_management(server) do | socket |
      socket.write "stats slabs\r\n"
      while line = socket.gets do
        raise_on_error_response! line
        break if line == "END\r\n"
        if line =~ /\ASTAT ((\d+):)?([\S]+) (\d+)/ then
          id, name, value = $2, $3, $4
          if id.nil? then
            stats[name] = value.to_i
          else
            if stats[id.to_i].nil? then
              stats[id.to_i] = {}
            end
            stats[id.to_i][name] = value.to_i
          end
        end
      end
    end
    stats
  end


  def cachedump server, slab_id, count
    keys = {}
    with_socket_management(server) do | socket |
      socket.write "stats cachedump #{ slab_id } #{ count }\r\n"
      while line = socket.gets do
        raise_on_error_response! line
        break if line == "END\r\n"
        if line =~ /\AITEM (.+) \[(\d+) b; ([\d]+) s\]/ then
          key, expiry = $1, $3.to_i
          keys[key] = expiry
        end
      end
    end
    keys
  end


  def dump_all
    servers.each do | server |
      slabs(server).each do | id, value |
        next if not id.kind_of? Integer
        cachedump(server, id, value[ "used_chunks" ]).each do | key, expiry |
        value = get(key)
        value = "(nil)" if value.nil?
        print "#{ key },#{ value },#{ Time.at(expiry).strftime("%F %T") }\n"
        end
      end
    end
  end


  def stats_all
    server_stats = stats
    server_stats.each do | key, stats |
      print "#{ key }\n"
      stats.sort.each do | key, value |
        print "  #{ key }=#{ value }\n"
      end
    end
  end


  def flush_all
    servers.each do | server |
      with_socket_management(server) do | socket |
        socket.write "flush_all\r\n"
        while line = socket.gets do
          raise_on_error_response! line
          break if line == "OK\r\n"
        end
      end
    end
  end
end


fdb = DumpFdb.new '127.0.0.1:11211'
command = ARGV.shift
if command == "stats" then
  fdb.stats_all
elsif command == "flush" then
  fdb.flush_all
else
  fdb.dump_all
end
